/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// LastRunStatusApplyConfiguration represents a declarative configuration of the LastRunStatus type for use
// with apply.
//
// LastRunStatus is the context of the most recent terminal derived run plus a
// snapshot of its RepackRunStatus (flattened via inline embed), so the run's
// name/mode/trigger/resource sit next to phase/plan/result under lastRunStatus.
type LastRunStatusApplyConfiguration struct {
	// Name of the run that produced this snapshot (named {policy}-{YYYYMMDDHHmmss}),
	// retained for tracing after the run is TTL/GC-deleted.
	Name *string `json:"name,omitempty"`
	// Mode is the run's repack mode (DryRun/Execute, from runTemplate.spec.mode).
	Mode *repackv1alpha1.RepackMode `json:"mode,omitempty"`
	// Trigger is the source that fired (cronSchedule|onFragAbovePercent), matching
	// the derived run's RepackTriggerLabel. Always set: a run is only created by a
	// firing source.
	Trigger *string `json:"trigger,omitempty"`
	// Resource is the target accelerator resource (RepackRun.spec.goals[0].resource);
	// empty when the template leaves goals unset.
	Resource                          *v1.ResourceName `json:"resource,omitempty"`
	RepackRunStatusApplyConfiguration `json:",inline"`
}

// LastRunStatusApplyConfiguration constructs a declarative configuration of the LastRunStatus type for use with
// apply.
func LastRunStatus() *LastRunStatusApplyConfiguration {
	return &LastRunStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithName(value string) *LastRunStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithMode(value repackv1alpha1.RepackMode) *LastRunStatusApplyConfiguration {
	b.Mode = &value
	return b
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithTrigger(value string) *LastRunStatusApplyConfiguration {
	b.Trigger = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithResource(value v1.ResourceName) *LastRunStatusApplyConfiguration {
	b.Resource = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithPhase(value repackv1alpha1.RepackPhase) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LastRunStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *LastRunStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.RepackRunStatusApplyConfiguration.Conditions = append(b.RepackRunStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithMessage(value string) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.Message = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithStartTime(value apismetav1.Time) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithCompletionTime(value apismetav1.Time) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.CompletionTime = &value
	return b
}

// WithExecutionDeadline sets the ExecutionDeadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExecutionDeadline field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithExecutionDeadline(value apismetav1.Time) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.ExecutionDeadline = &value
	return b
}

// WithPlan sets the Plan field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Plan field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithPlan(value *RepackPlanApplyConfiguration) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.Plan = value
	return b
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *LastRunStatusApplyConfiguration) WithResult(value *RepackResultApplyConfiguration) *LastRunStatusApplyConfiguration {
	b.RepackRunStatusApplyConfiguration.Result = value
	return b
}

// WithRelocations adds the given value to the Relocations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Relocations field.
func (b *LastRunStatusApplyConfiguration) WithRelocations(values ...*PodRelocationStatusApplyConfiguration) *LastRunStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRelocations")
		}
		b.RepackRunStatusApplyConfiguration.Relocations = append(b.RepackRunStatusApplyConfiguration.Relocations, *values[i])
	}
	return b
}
